void _puts_recursion(char *s);
int _putchar(char c);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int is_palindrome(char *s);
int _sqrt_rec(int n, int x);
int is_prime(int n, int x);
int palindrome(char *s, int first, int last);
int _strlen_recursion(char *s);
